services:
  proxy:
    image: envoyproxy/envoy:v1.34.1
    entrypoint: /usr/local/bin/envoy -c /etc/envoy.yaml -l info --service-cluster proxy
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy.yaml
      - ./target/wasm32-unknown-unknown/release/wasmstreamcontext.wasm:/etc/wasmstreamcontext.wasm
    networks:
      - envoymesh
    ports:
      - "19000:10000"

networks:
  envoymesh:
    ipam:
      config:
        - subnet: 172.21.0.0/16
