version: "3.8"
services:
  proxy:
    image: envoyproxy/envoy:v1.33-latest
    entrypoint: /usr/local/bin/envoy -c /etc/envoy.yaml -l debug --service-cluster proxy
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy.yaml
      - ./target/wasm32-unknown-unknown/release/wasmstreamcontext.wasm:/etc/wasmstreamcontext.wasm
    networks:
      - envoymesh
    ports:
      - "19000:10000"

networks:
  envoymesh: {}
